### ISSUE TITLE
Property 'provider' does not exist on type 'JsonRpcProvider'

### ISSUE THREAD

**Issue by Doko-Demo-Doa** [TrueFiEng/useDApp#502]
It happens when updating `@usedapp/core` from 0.9.1 to 0.10.0

**Comment by vanruch** [comment]
Is it a typescript issue? When does it happen?

**Comment by Doko-Demo-Doa** [comment]
Yes, from typescript. Originally it is:

```
const { library } = useEthers()

library.provider // << provider does not exist
```

Did I miss something?

**Comment by vanruch** [comment]
You'd have to check if library is a Web3Provider

**Comment by noobshow** [comment]
library can't/shouldn't be Web3Provider i guess, shouldn't it be JSONRPCProvider?

**Comment by vanruch** [comment]
Web3Provider is derived from JsonRPCProvider so the library would usually be Web3Provider but you'd have to check it with
`library instanceof Web3Provider`

**Comment by Doko-Demo-Doa** [comment]
I think there is still a problem. If I check its instance:

![image](https://user-images.githubusercontent.com/7723097/153562652-a5949d38-8406-4877-8f05-834e97ba6bc4.png)

It is clearly a Web3Provider instance, but if I check it with `instanceof`, it is always `false`

```ts
import { Web3Provider } from "@ethersproject/providers"

console.log(library instanceof Web3Provider) // Always false
```

**Comment by SeanZom** [comment]
@Doko-Demo-Doa 
```javascript
library instanceof Web3Provider; // true

did you check if `library` isn't ready when you log it?



```
works for me when `library` is available



> I think there is still a problem. If I check its instance:
> 
> ![image](https://user-images.githubusercontent.com/7723097/153562652-a5949d38-8406-4877-8f05-834e97ba6bc4.png)
> 
> It is clearly a Web3Provider instance, but if I check it with `instanceof`, it is always `false`
> 
> ```ts
> import { Web3Provider } from "@ethersproject/providers"
> 
> console.log(library instanceof Web3Provider) // Always false
> ```

**Comment by rzadp** [comment]
> It is clearly a Web3Provider instance, but if I check it with `instanceof`, it is always `false`
> 
> ```ts
> import { Web3Provider } from "@ethersproject/providers"
> 
> console.log(library instanceof Web3Provider) // Always false
> ```

This might be a mistmatch of your `@ethersproject/providers` version on what is being used inside of useDapp.

UseDapp 1.0 allow you to set your own provider in `readOnlyUrls`, so you can feed your own provider into the config which will work the way you expect.
